bitdriftlabs/pulse

- Cargo.lock
- Cargo.toml
- pulse-metrics/src/pipeline/processor/mutate/mod_test.rs
- pulse-metrics/src/protos/metric.rs
- pulse-metrics/src/vrl/mod.rs
> implement VRL del() support for tags

- pulse-metrics/src/pipeline/processor/mutate/mod_test.rs
- pulse-metrics/src/protos/metric.rs
If there has been deletion we need to clear the metrics cache. Also improve test coverage over the rest of this path.
> fix bug in previous commit

- Cargo.lock
- pulse-metrics/src/pipeline/inflow/wire/udp.rs
- pulse-metrics/src/pipeline/inflow/wire/util.rs
- pulse-protobuf/proto/pulse/config/inflow/v1/wire.proto
- pulse-protobuf/src/protos/pulse/config/inflow/v1/wire.rs
- pulse-proxy/Cargo.toml
- pulse-proxy/src/test/integration/statsd.rs
This is similar to my previous commit, but for UDP. If configured, it creates UDP "sessions" which have a pre-buffer config as well as a session idle timeout.
Fixes BIT-3990
> add UDP pre-buffering

- pulse-metrics/src/pipeline/processor/cardinality_limiter/mod.rs
- pulse-metrics/src/vrl/mod.rs
- pulse-protobuf/proto/pulse/vrl_tester/v1/vrl_tester.proto
- pulse-protobuf/src/protos/pulse/vrl_tester/v1/vrl_tester.rs
- pulse-vrl-tester/src/lib.rs
- pulse-vrl-tester/src/test/mod.rs
> vrl tester: allow testing cardinality limiter programs

- pulse-metrics/src/pipeline/processor/aggregation/mod.rs
- pulse-metrics/src/pipeline/processor/aggregation/mod_test.rs
- pulse-metrics/src/pipeline/processor/aggregation/test/mod.rs
- pulse-metrics/src/pipeline/processor/internode/convert_test.rs
I don't see how this can happen but this would cause the issue we are seeing and should give us more info either way.
> Protect against empty bulk timers

- pulse-metrics/src/admin/stats.rs
- pulse-metrics/src/admin/stats_test.rs
- pulse-metrics/src/pipeline/inflow/wire/pre_buffer.rs
- pulse-metrics/src/pipeline/outflow/prom/remote_write.rs
- pulse-metrics/src/pipeline/processor/aggregation/mod.rs
- pulse-metrics/src/pipeline/processor/aggregation/mod_test.rs
- pulse-metrics/src/pipeline/processor/aggregation/reservoir_timer.rs
- pulse-metrics/src/protos/metric.rs
- pulse-metrics/src/protos/metric_test.rs
- pulse-metrics/src/protos/prom.rs
- pulse-metrics/src/protos/prom_test.rs
- pulse-promcli/src/main.rs
- pulse-proxy/src/test/integration/complex_config.rs
- pulse-proxy/src/test/integration/mod.rs
Also clean up some empty bulk timer debugging in places where it can't happen. Finally, re-add stats_test and clean up as it was in the tree but not compiled and run.
Fixes BIT-4387
> prom: add change type tracker with metrics

- Cargo.lock
- Cargo.toml
- pulse-metrics/src/metric_generator.rs
- pulse-metrics/src/pipeline/time.rs
- pulse-metrics/src/protos/carbon.rs
- pulse-metrics/src/protos/carbon_test.rs
- pulse-metrics/src/protos/prom.rs
- pulse-metrics/src/reservoir_timer.rs
Bump deps including nom which was non-trivial.
> prom: add more metadata logs for debugging

- Cargo.lock
- Cargo.toml
- pulse-metrics/src/pipeline/inflow/wire/pre_buffer.rs
- pulse-metrics/src/pipeline/inflow/wire/tcp.rs
- pulse-metrics/src/pipeline/inflow/wire/udp.rs
- pulse-metrics/src/pipeline/inflow/wire/util.rs
- pulse-protobuf/proto/pulse/config/inflow/v1/wire.proto
- pulse-protobuf/src/protos/pulse/config/inflow/v1/wire.rs
Also change default back to 100. With bulk timer optimization there should not be much perf difference.
Fixes BIT-4567
> pre-buffer: add config for timer reservoir size

- pulse-metrics/src/pipeline/inflow/prom_scrape/scraper.rs
- pulse-metrics/src/pipeline/inflow/prom_scrape/scraper_test.rs
> Trim white space from port list

- pulse-metrics/src/pipeline/inflow/prom_scrape/scraper.rs
- pulse-metrics/src/pipeline/inflow/prom_scrape/scraper_test.rs
- pulse-protobuf/proto/pulse/config/inflow/v1/k8s_prom.proto
- pulse-protobuf/src/protos/pulse/config/inflow/v1/k8s_prom.rs
Add TLS config as per https://prometheus.io/docs/prometheus/latest/configuration/configuration/#tls_config
In the Next PR we will address insecure_skip_verify:
> Add tls config

- Cargo.lock
- Cargo.toml
- pulse-metrics/src/protos/metric.rs
- pulse-metrics/src/protos/statsd.rs
- pulse-metrics/src/protos/statsd_test.rs
- pulse-protobuf/proto/pulse/config/common/v1/common.proto
- pulse-protobuf/src/protos/pulse/config/common/v1/common.rs
- pulse-vrl-tester/Cargo.toml
- pulse-vrl-tester/src/lib.rs
> statsd: add option to sanitize tag names and values

- Cargo.lock
- Cargo.toml
- pulse-metrics/src/clients/prom.rs
- pulse-metrics/src/pipeline/inflow/prom_scrape/scraper.rs
- pulse-metrics/src/pipeline/outflow/prom/retry_offload.rs
Attempt to print the inner error from the library.
> scraper: improve error when request fails

- pulse-metrics/src/pipeline/inflow/prom_scrape/scraper.rs
- pulse-metrics/src/pipeline/inflow/prom_scrape/scraper_test.rs
- pulse-protobuf/proto/pulse/config/inflow/v1/k8s_prom.proto
- pulse-protobuf/src/protos/pulse/config/inflow/v1/k8s_prom.rs
Defaults to 15s. Also don't wait for scrapers to join on reload. The theory being that the reload task is hanging due to hung request.
> k8s scraping: add timeout

- pulse-common/src/k8s/pods_info.rs
We should be ok with eventually consistent and this will put less load on the API server.
> k8s watch: use resourceVersion 0 for lists

- pulse-common/src/k8s/mod.rs
- pulse-common/src/k8s/pods_info.rs
Apparently limit is ignored when this is set so the library was refusing to set it. See code comments for more info.
> k8s: actually set resourceVersion=0

- Cargo.lock
- Cargo.toml
- pulse-common/src/k8s/pods_info.rs
- pulse-common/src/k8s/pods_info_test.rs
- pulse-metrics/Cargo.toml
- pulse-metrics/src/pipeline/inflow/prom_scrape/scraper.rs
- pulse-metrics/src/pipeline/inflow/prom_scrape/scraper_test.rs
- pulse-protobuf/proto/pulse/config/inflow/v1/k8s_prom.proto
- pulse-protobuf/src/protos/pulse/config/inflow/v1/k8s_prom.rs
1) Support prometheus.io/scheme annotation
2) Support named service ports
3) Allow endpoing service to use k8s service auth
Fixes BIT-4892
> various k8s scraper improvements

- pulse-common/src/k8s/mod.rs
- pulse-common/src/k8s/pods_info.rs
- pulse-common/src/k8s/pods_info_test.rs
- pulse-common/src/k8s/test/mod.rs
- pulse-common/src/metadata.rs
- pulse-metrics/src/pipeline/inflow/prom_scrape/parser_test.rs
- pulse-metrics/src/pipeline/inflow/prom_scrape/scraper.rs
- pulse-metrics/src/pipeline/inflow/prom_scrape/scraper_test.rs
- pulse-metrics/src/pipeline/processor/cardinality_limiter/mod.rs
- pulse-metrics/src/pipeline/processor/cardinality_limiter/mod_test.rs
- pulse-metrics/src/pipeline/processor/mutate/mod_test.rs
- pulse-metrics/src/test/mod.rs
- pulse-protobuf/proto/pulse/config/processor/v1/mutate.proto
- pulse-proxy/src/test/integration/mod.rs
- pulse-vrl-tester/src/lib.rs
Also provide node only metadata to NodeEndpoints target
Fixes BIT-4936
> VRL: add node labels and annotations to metadata

- Cargo.toml
- pulse-metrics/src/pipeline/inflow/prom_scrape/http_sd.rs
- pulse-metrics/src/pipeline/inflow/prom_scrape/mod.rs
- pulse-metrics/src/pipeline/inflow/prom_scrape/parser.rs
- pulse-metrics/src/pipeline/inflow/prom_scrape/parser_test.rs
- pulse-metrics/src/pipeline/inflow/prom_scrape/scraper.rs
- pulse-metrics/src/pipeline/inflow/prom_scrape/scraper_test.rs
- pulse-protobuf/proto/pulse/config/inflow/v1/k8s_prom.proto
- pulse-protobuf/src/protos/pulse/config/inflow/v1/k8s_prom.rs
> prom scraper: implement HTTP SD protocol

- pulse-common/src/k8s/mod.rs
- pulse-common/src/k8s/pods_info.rs
- pulse-common/src/k8s/pods_info_test.rs
- pulse-common/src/k8s/services.rs
- pulse-common/src/k8s/services_test.rs
- pulse-common/src/k8s/test/mod.rs
- pulse-metrics/src/pipeline/inflow/prom_scrape/scraper_test.rs
- pulse-protobuf/proto/pulse/config/bootstrap/v1/bootstrap.proto
- pulse-protobuf/src/protos/pulse/config/bootstrap/v1/bootstrap.rs
Instead of fetching all services, fetch by namespace on demand and cache for a configurable period. This will perform a lot better.
Fixes BIT-4919
> k8s: rewrite service cache

- pulse-metrics/src/pipeline/processor/mutate/mod.rs
- pulse-metrics/src/pipeline/processor/mutate/mod_test.rs
- pulse-metrics/src/vrl/mod.rs
- pulse-protobuf/proto/pulse/config/processor/v1/mutate.proto
- pulse-proxy/src/test/integration/blocklisting.rs
- pulse-vrl-tester/src/lib.rs
Fixes BIT-5140
Also commit an integration test for the block all elision config.
> vrl: add ability to flatten prom histogram and summaries

- pulse-metrics/src/pipeline/inflow/otlp/mod.rs
- pulse-metrics/src/pipeline/outflow/otlp/mod.rs
OTLP uses framed snappy vs. block snappy.
> fix otlp snappy

- Cargo.lock
- pulse-common/Cargo.toml
- pulse-common/src/k8s/pods_info.rs
- pulse-common/src/k8s/pods_info_test.rs
- pulse-metrics/src/pipeline/inflow/prom_scrape/scraper_test.rs
- pulse-metrics/src/pipeline/processor/cardinality_limiter/mod_test.rs
- pulse-protobuf/proto/pulse/config/bootstrap/v1/bootstrap.proto
- pulse-protobuf/src/protos/pulse/config/bootstrap/v1/bootstrap.rs
- pulse-proxy/src/lib.rs
- pulse-proxy/src/main.rs
- pulse-proxy/src/test/integration/complex_config.rs
- pulse-proxy/src/test/integration/mod.rs
- pulse-proxy/src/test/integration/statsd.rs
> support host network filtering

- Cargo.lock
- Cargo.toml
- pulse-metrics/src/pipeline/inflow/prom_scrape/scraper.rs
- pulse-metrics/src/pipeline/inflow/prom_scrape/scraper_test.rs
- pulse-protobuf/proto/pulse/config/inflow/v1/k8s_prom.proto
- pulse-protobuf/src/protos/pulse/config/inflow/v1/k8s_prom.rs
> k8s scraper: allow overriding default prom annotations
